import { TMatrix } from '../../../wave-algorithm/models';

export const getScheme = (): TMatrix => {
    return [
        [
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
        ],
        [
            { type: 'way-forbidden', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'way-forbidden', value: 0 },
        ],
        [
            { type: 'way-forbidden', value: 0 },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'way-forbidden', value: 0 },
        ],
        [
            { type: 'way-forbidden', value: 0 },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'way-forbidden', value: 0 },
        ],
        [
            { type: 'way-forbidden', value: 0 },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'forbidden', value: 0, color: 'lightblue' },
            { type: 'way-forbidden', value: 0 },
        ],
        [
            { type: 'way-forbidden', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0, color: 'red' },
            { type: 'way-forbidden', value: 0 },
            { type: 'way-forbidden', value: 0 },
        ],
        [
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
            { type: 'way-forbidden', value: 0 },
            { type: 'free', value: 0 },
        ],
    ]
}